---
title: "Gov 50 Final Project"
author: "Juan C. Venancio"
description: "Gov 50 Immigration Project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to Mexico's evolving role as a destination country for many immigrants. Over the last decade, there has been a significant increase in asylum applications of immigrants attempting to permamently resettle in the country. I would like to explore this phenomenon, and compile/analyze data that showcase this recent trend over time. I am planning to use data from the Mexican Commission for Refugee Assistance. 


## Project Abstract 

Does the type of asylum claim affect the percentage of asylum seekers that get refugee status granted in Mexico? In my research project, I hypothesize, that migrants who indicate political and humanitarian reasons for emigration from their country of origin tend to have higher possibilities to successfully obtain refugee status in Mexico. As a result, I expect that migrants who only file "economic reasons" for seeking asylum tend to have lower possibilities at refugee resettlement. Additionally, though the Mexican Government has made advances to expand their refugee granting criteria, because the 1951 UN Convention of Refugees provides a large number of successful reugee claims to migrants with "well-founded fear of persecution", then I also predict that Mexican institutions reject non-political actors at a significant larger rate. For this project, I will analyze the Mexican Government's Commission on Refugee Assistance open data set that I will use to assess the several reasons that migrants tend to leave their countries of origin. My unit of measurement is whether an immigrant was granted refugee status or not. If the immigrant was provided with a refugee status, implying that the migrant was considered to have had a well-founded fear of persecution, then I will indicate that with 1 for successful application. If a migrant was rejected, then I will indicate that with 0. The independent variable will be described as "having migrated because of 'Political', 'Economic', 'Social'", or other reasons. The explanatory variable of interest is whether claiming a certain reason for migrating will grant you more of a benefit or not in refugee resettlement. If political/humanitarian applications have a higher rate of refugee success, then that will make my hypothesis correct. If other types of applications have a higher rate of success, then I will be proven wrong. In any case, I am also interested in observing the variability of application success and the type of application submitted. 